services:
  instant-wellness-kits:
    image: voloshmiak/instant-wellness-kits:0.0.5
    container_name: instant-wellness-kits
    hostname: instant-wellness-kits
    networks:
      - betterme-network
    ports:
      - "80:80"
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PORT=80
      - GEOCODING_API_KEY=${GEOCODING_API_KEY}
      - ENV=DEV
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_USER_PASSWORD=password
      - DB_HOST=postgres
      - DB_PORT=5432
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:80/health" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s

  betterme-frontend:
    image: voloshmiak/better-me-frontend:0.0.6
    container_name: betterme-frontend
    hostname: betterme-frontend
    networks:
      - betterme-network
    ports:
      - "5173:80"
    restart: on-failure
    depends_on:
      instant-wellness-kits:
        condition: service_healthy
    environment:
      - VITE_API_URL=http://localhost:80

  postgres:
    image: postgres:18
    container_name: postgres
    hostname: postgres
    networks:
      - betterme-network
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 60s

networks:
  betterme-network:
    driver: bridge

volumes:
  postgres-data: